name: Build Back
description: Build the Tauri desktop backend

runs:
  using: composite
  steps:
    - name: Download dist artifact
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/

    - name: Install Linux dependencies
      uses: ./.github/workflows/actions/install-linux-deps

    - name: Build Tauri
      shell: bash
      run: cargo build --release --manifest-path src-tauri/Cargo.toml
