name: Quality Back
description: Run rustfmt and clippy checks

runs:
  using: composite
  steps:
    - name: rustfmt check
      shell: bash
      run: cargo fmt --manifest-path src-tauri/Cargo.toml --all -- --check

    - name: clippy check
      shell: bash
      run: cargo clippy --manifest-path src-tauri/Cargo.toml
